name: Release

on:
    push:
        tags:
            - 'v*.*.*'

permissions:
    contents: write

jobs:
    publish-release:
        runs-on: ubuntu-latest
        if: github.repository == 'ttypic/swift-klib-plugin'
        timeout-minutes: 25

        steps:
            - uses: actions/checkout@v4
            - uses: gradle/wrapper-validation-action@v2
            - uses: actions/setup-java@v4
              with:
                  distribution: 'zulu'
                  java-version: '17'
                  check-latest: true

              run: ./gradlew --stacktrace :plugin:publishPlugins
              env:
                  GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
                  GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}

            - name: Extract release notes
              id: release_notes
              uses: ffurrer2/extract-release-notes@v2

            - name: Create release
              uses: softprops/action-gh-release@v2
              with:
                  body: ${{ steps.release_notes.outputs.release_notes }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
